.PHONY: all clean
all: color-interpolate-by-luminance

color-interpolate-by-luminance: color-interpolate-by-luminance.go
	go build color-interpolate-by-luminance.go

clean: 
	rm -v color-interpolate-by-luminance
